version: "3.7"
services:
  marquez-api:
    image: marquezproject/marquez:0.50.0
    container_name: marquez-api
    environment:
      - MARQUEZ_PORT=5000
      - POSTGRES_HOST=marquez-db
      - SEARCH_ENABLED=false
    ports:
      - 5000:5000
    depends_on:
      marquez-db:
        condition: service_healthy

  web:
    image: "marquezproject/marquez-web:0.50.0"
    container_name: marquez-web
    environment:
      - MARQUEZ_HOST=marquez-api
      - MARQUEZ_PORT=5000
      - WEB_PORT=3000
    ports:
      - 3000:3000
    depends_on:
      - marquez-api


  marquez-db:
    image: postgres:14
    environment:
      POSTGRES_USER: marquez
      POSTGRES_PASSWORD: marquez
      POSTGRES_DB: marquez
    volumes:
      - marquez-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "marquez"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

volumes:
  marquez-db-volume:
