
version: 2

models:
  - name: countries
    description: "Table containing speakers' countries"
    columns:
      - name: speaker_id
        tests:
          - unique
          - not_null
      - name: name
        description: "The name of the country"
        tests:
          - not_null
  - name: countries_performance
    columns:
      - name: country_name
        tests:
          - not_null
      - name: attendees_count
        tests:
          - not_null

sources:
  - name: dss
    database: airflow
    schema: public
    tables:
      - name: session_performance
        columns:
          - name: session_id
          - name: attendees_count
          - name: speaker_name